[package]
name = "rcore_fork"
version = "0.1.0"
edition = "2021"

[dependencies]
sbi-rt = { version = "0.0.3", features = ["legacy"] }
log = "0.4"


[target.'cfg(target_arch = "riscv64")'.dependencies]